{   CustomMenu
    Copyright (C) 2022-2099 Baz Cuda
    https://github.com/BazzaCuda/CustomMenu

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307, USA
}
unit shellFoldersDef;

interface

const
  shellFoldersNameArray: TArray<string> = [
    'Account Pictures',
    'Add New Programs',
    'Administrative Tools',
    'All Tasks (aka "God Mode")',
    'AppData Folder',
    'Application Shortcuts',
    'Apps Folder',
    'App Updates Folder',
    'Cache',
    'Camera Roll',
    'CD Burning',
    'Change/Remove Programs Folder',
    'Common Administrative Tools',
    'Common AppData (ProgramData)',
    'Common Desktop',
    'Common Documents',
    'Common Programs',
    'Common Start Menu',
    'Common Startup',
    'Common Templates',
    'Common Downloads',
    'Common Music',
    'Common Pictures',
    'Common Ringtones',
    'Common Video',
    'Conflict Folder',
    'Connections Folder',
    'Contacts',
    'Control Panel (Full)',
    'Cookies',
    'Credentials Manager',
    'Crypto Keys',
    'CSC Folder',
    'Desktop',
    'Device Metadata Store',
    'Documents Library',
    'Downloads',
    'DP API Keys',
    'Favorites',
    'Fonts',
    'Games',
    'Game Tasks',
    'History',
    'Home Group Current User Folder',
    'Home Group Folder',
    'Implicit App Shortcuts',
    'Internet Folder',
    'Libraries',
    'Links',
    'Local AppData',
    'Local AppData Low',
    'Localized Resources Dir',
    'MAPI Folder',
    'Music Library',
    'My Music',
    'My Pictures',
    'My Video',
    'My Computer',
    'NetHood',
    'Network Places',
    'OEM Links',
    'OneDrive',
    'Original Images',
    'Personal Documents',
    'Photo Albums',
    'Pictures Library',
    'Playlists',
    'Printers Folder',
    'PrintHood',
    'Profile',
    'ProgramFiles',
    'ProgramFiles Common',
    'ProgramFiles CommonX64',
    'ProgramFiles CommonX86',
    'ProgramFiles X64',
    'ProgramFiles X86',
    'Programs',
    'Public',
    'Public Account Pictures',
    'Public Game Tasks',
    'Public Libraries',
    'Quick Launch',
    'Recent',
    'Recorded TV Library',
    'Recycle Bin',
    'Resource Dir',
    'Retail Demo',
    'Ringtones',
    'Roamed Tile Images',
    'Roaming Tiles',
    'Saved Games',
    'Screenshots',
    'Searches',
    'Search History',
    'Search Home Folder',
    'Search Templates Folder',
    'SendTo',
    'SkyDrive Camera Roll',
    'SkyDrive Documents',
    'SkyDrive Music',
    'SkyDrive Pictures',
    'Start Menu',
    'Start Menu All Programs',
    'Startup',
    'Sync Center Folder',
    'Sync Results Folder',
    'Sync Setup Folder',
    'System',
    'System Certificates',
    'SystemX86',
    'Templates',
    'This PC Desktop',
    'User Pinned',
    'User Profiles',
    'User Program Files',
    'User Program Files Common',
    'User profile Folder',
    'User''s Libraries Folder',
    'Videos Library',
    'Windows'
];

  shellFoldersCmdArray: TArray<string> = [
    'shell:AccountPictures',
    'shell:AddNewProgramsFolder',
    'shell:Administrative Tools',
    'shell:::{ED7BA470-8E54-465E-825C-99712043E01C}',
    'shell:AppData',
    'shell:Application Shortcuts',
    'shell:AppsFolder',
    'shell:AppUpdatesFolder',
    'shell:Cache',
    'shell:Camera Roll',
    'shell:CD Burning',
    'shell:ChangeRemoveProgramsFolder',
    'shell:Common Administrative Tools',
    'shell:Common AppData',
    'shell:Common Desktop',
    'shell:Common Documents',
    'shell:Common Programs',
    'shell:Common Start Menu',
    'shell:Common Startup',
    'shell:Common Templates',
    'shell:CommonDownloads',
    'shell:CommonMusic',
    'shell:CommonPictures',
    'shell:CommonRingtones',
    'shell:CommonVideo',
    'shell:ConflictFolder',
    'shell:ConnectionsFolder',
    'shell:Contacts',
    'shell:ControlPanelFolder',
    'shell:Cookies',
    'shell:CredentialManager',
    'shell:CryptoKeys',
    'shell:CSCFolder',
    'shell:Desktop',
    'shell:Device Metadata Store',
    'shell:DocumentsLibrary',
    'shell:Downloads',
    'shell:DpapiKeys',
    'shell:Favorites',
    'shell:Fonts',
    'shell:Games',
    'shell:GameTasks',
    'shell:History',
    'shell:HomeGroupCurrentUserFolder',
    'shell:HomeGroupFolder',
    'shell:ImplicitAppShortcuts',
    'shell:InternetFolder',
    'shell:Libraries',
    'shell:Links',
    'shell:Local AppData',
    'shell:LocalAppDataLow',
    'shell:LocalizedResourcesDir',
    'shell:MAPIFolder',
    'shell:MusicLibrary',
    'shell:My Music',
    'shell:My Pictures',
    'shell:My Video',
    'shell:MyComputerFolder',
    'shell:NetHood',
    'shell:NetworkPlacesFolder',
    'shell:OEM Links',
    'shell:OneDrive',
    'shell:Original Images',
    'shell:Personal',
    'shell:PhotoAlbums',
    'shell:PicturesLibrary',
    'shell:Playlists',
    'shell:PrintersFolder',
    'shell:PrintHood',
    'shell:Profile',
    'shell:ProgramFiles',
    'shell:ProgramFilesCommon',
    'shell:ProgramFilesCommonX64',
    'shell:ProgramFilesCommonX86',
    'shell:ProgramFilesX64',
    'shell:ProgramFilesX86',
    'shell:Programs',
    'shell:Public',
    'shell:PublicAccountPictures',
    'shell:PublicGameTasks',
    'shell:PublicLibraries',
    'shell:Quick Launch',
    'shell:Recent',
    'shell:RecordedTVLibrary',
    'shell:RecycleBinFolder',
    'shell:ResourceDir',
    'shell:Retail Demo',
    'shell:Ringtones',
    'shell:Roamed Tile Images',
    'shell:Roaming Tiles',
    'shell:SavedGames',
    'shell:Screenshots',
    'shell:Searches',
    'shell:SearchHistoryFolder',
    'shell:SearchHomeFolder',
    'shell:SearchTemplatesFolder',
    'shell:SendTo',
    'shell:SkyDriveCameraRoll',
    'shell:SkyDriveDocuments',
    'shell:SkyDriveMusic',
    'shell:SkyDrivePictures',
    'shell:Start Menu',
    'shell:StartMenuAllPrograms',
    'shell:Startup',
    'shell:SyncCenterFolder',
    'shell:SyncResultsFolder',
    'shell:SyncSetupFolder',
    'shell:System',
    'shell:SystemCertificates',
    'shell:SystemX86',
    'shell:Templates',
    'shell:ThisPCDesktopFolder',
    'shell:User Pinned',
    'shell:UserProfiles',
    'shell:UserProgramFiles',
    'shell:UserProgramFilesCommon',
    'shell:UsersFilesFolder',
    'shell:UsersLibrariesFolder',
    'shell:VideosLibrary',
    'shell:Windows'
];

implementation

end.
